In [1]:
import tensorflow.keras
from PIL import Image, ImageOps
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
# img = Image.open('normal.png').convert('LA')
# img.save('normal gray.png')


    
# Disable scientific notation for clarity
# np.set_printoptions(suppress=True)

# # Load the model
# model = tensorflow.keras.models.load_model('keras_model.h5')

# # Create the array of the right shape to feed into the keras model
# # The 'length' or number of images you can put into the array is
# # determined by the first position in the shape tuple, in this case 1.
# data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

# Replace this with the path to your image
# image = Image.open('normal gray.png').convert('RGB')


cap = cv2.VideoCapture(0)
cap.set(3, 224)
cap.set(4, 224)
print('load')
while True:
    ret, frame = cap.read()
    if frame is None:
        print('No Frame')
        break
    print(frame)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('frame', gray)
    image = frame
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

    #resize the image to a 224x224 with the same strategy as in TM2:
    #resizing the image to be at least 224x224 and then cropping from the center
    # size = (224, 224)
    # image = ImageOps.fit(image, size, Image.ANTIALIAS)

    # #turn the image into a numpy array
    # image_array = np.asarray(image)

    # # display the resized image
    # # image.show()

    # # Normalize the image
    # normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1

    # # Load the image into the array
    # data[0] = normalized_image_array

    # # run the inference
    # prediction = model.predict(data)
    # print(prediction)
    



load
[[[10 14 10]
  [10 14 10]
  [10 14 10]
  ...
  [ 0  2  0]
  [ 0  2  0]
  [ 0  3  0]]

 [[12 14 12]
  [13 16 13]
  [12 14 12]
  ...
  [ 0  2  0]
  [ 0  2  0]
  [ 0  3  0]]

 [[13 15 14]
  [13 15 14]
  [13 15 14]
  ...
  [ 0  2  0]
  [ 0  2  0]
  [ 0  2  0]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  6  2]
  [ 2  6  2]
  [ 3  5  2]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  6  2]
  [ 2  5  2]
  [ 2  5  2]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 2  7  4]
  [ 3  7  4]
  [ 2  5  2]]]
[[[128 138 141]
  [128 138 141]
  [127 137 140]
  ...
  [ 75  94 105]
  [ 76  95 106]
  [ 78  97 108]]

 [[132 142 144]
  [134 144 147]
  [133 143 145]
  ...
  [ 73  92 102]
  [ 76  95 106]
  [ 75  94 104]]

 [[134 145 146]
  [135 146 147]
  [136 146 147]
  ...
  [ 73  92 101]
  [ 71  91 101]
  [ 68  87  98]]

 ...

 [[ 33  39  42]
  [ 33  39  42]
  [ 31  36  40]
  ...
  [104 129 141]
  [105 130 142]
  [107 133 144]]

 [[ 31  36  40]
  [ 30  35  39]
  [ 32  37  41]
  .

[[[119 127 135]
  [116 125 133]
  [117 126 134]
  ...
  [ 62  82  90]
  [ 63  83  91]
  [ 62  82  90]]

 [[121 130 137]
  [120 129 136]
  [120 129 136]
  ...
  [ 62  82  90]
  [ 61  81  89]
  [ 60  80  88]]

 [[124 134 140]
  [125 134 140]
  [126 134 140]
  ...
  [ 62  82  90]
  [ 61  81  89]
  [ 57  77  85]]

 ...

 [[ 20  24  25]
  [ 21  25  26]
  [ 16  22  23]
  ...
  [ 93 122 136]
  [ 93 122 137]
  [ 91 120 136]]

 [[ 22  26  28]
  [ 22  26  28]
  [ 19  24  25]
  ...
  [ 92 122 137]
  [ 90 121 136]
  [ 89 119 135]]

 [[ 22  26  28]
  [ 22  26  28]
  [ 20  25  27]
  ...
  [ 93 123 138]
  [ 90 121 136]
  [ 87 118 134]]]
[[[117 127 132]
  [117 127 132]
  [119 128 133]
  ...
  [ 61  81  89]
  [ 60  80  88]
  [ 61  81  89]]

 [[122 131 135]
  [120 129 134]
  [121 131 135]
  ...
  [ 60  80  88]
  [ 59  79  87]
  [ 59  79  87]]

 [[126 134 138]
  [126 134 138]
  [124 133 137]
  ...
  [ 62  82  90]
  [ 60  80  88]
  [ 59  79  86]]

 ...

 [[ 21  25  27]
  [ 22  26  28]
  [ 18  24  25]
  ..

[[[119 128 133]
  [120 129 135]
  [120 129 135]
  ...
  [ 64  86  94]
  [ 64  86  94]
  [ 65  87  95]]

 [[122 132 137]
  [123 133 138]
  [123 133 138]
  ...
  [ 64  86  93]
  [ 65  87  94]
  [ 65  87  94]]

 [[125 135 138]
  [126 136 139]
  [126 136 139]
  ...
  [ 64  87  92]
  [ 65  88  93]
  [ 60  83  89]]

 ...

 [[ 21  25  27]
  [ 22  26  28]
  [ 22  26  29]
  ...
  [ 97 123 137]
  [ 99 125 140]
  [ 97 124 138]]

 [[ 21  24  28]
  [ 21  24  28]
  [ 22  25  29]
  ...
  [ 96 122 138]
  [ 97 124 139]
  [ 96 122 138]]

 [[ 20  23  27]
  [ 21  24  28]
  [ 22  25  29]
  ...
  [ 92 119 135]
  [ 94 120 136]
  [ 94 120 136]]]
[[[120 130 133]
  [121 131 134]
  [120 130 133]
  ...
  [ 64  85  95]
  [ 65  86  96]
  [ 66  87  97]]

 [[122 133 135]
  [123 134 136]
  [122 133 135]
  ...
  [ 64  85  95]
  [ 64  85  95]
  [ 64  85  95]]

 [[123 134 136]
  [125 135 138]
  [126 136 139]
  ...
  [ 65  86  96]
  [ 65  86  96]
  [ 61  83  93]]

 ...

 [[ 22  26  28]
  [ 21  25  27]
  [ 17  23  24]
  ..

[[[120 130 133]
  [120 130 133]
  [122 133 135]
  ...
  [ 60  84  94]
  [ 62  86  94]
  [ 62  86  93]]

 [[122 133 135]
  [122 133 135]
  [126 136 139]
  ...
  [ 61  85  93]
  [ 59  84  91]
  [ 58  83  90]]

 [[125 135 138]
  [126 136 139]
  [129 140 142]
  ...
  [ 60  83  92]
  [ 58  83  90]
  [ 55  81  88]]

 ...

 [[ 22  26  28]
  [ 24  27  29]
  [ 20  23  27]
  ...
  [ 97 124 138]
  [ 96 123 137]
  [ 98 125 139]]

 [[ 20  24  25]
  [ 24  27  29]
  [ 22  26  29]
  ...
  [ 96 124 138]
  [ 94 123 137]
  [ 97 126 139]]

 [[ 20  24  25]
  [ 21  25  27]
  [ 25  28  31]
  ...
  [ 93 122 136]
  [ 93 122 136]
  [ 91 121 134]]]
[[[120 130 133]
  [120 130 133]
  [121 131 135]
  ...
  [ 60  84  94]
  [ 62  86  94]
  [ 60  85  92]]

 [[122 132 136]
  [125 135 138]
  [126 135 140]
  ...
  [ 59  83  92]
  [ 59  84  91]
  [ 58  83  90]]

 [[125 134 139]
  [127 136 141]
  [129 139 144]
  ...
  [ 59  84  91]
  [ 58  83  90]
  [ 58  83  90]]

 ...

 [[ 20  27  28]
  [ 21  28  29]
  [ 20  26  29]
  ..

[[[116 127 132]
  [116 127 132]
  [114 126 131]
  ...
  [ 60  82  92]
  [ 61  83  93]
  [ 62  84  94]]

 [[119 131 135]
  [119 131 135]
  [119 131 135]
  ...
  [ 62  84  94]
  [ 62  84  94]
  [ 62  84  94]]

 [[123 135 138]
  [124 136 139]
  [124 136 139]
  ...
  [ 62  86  94]
  [ 64  87  95]
  [ 59  81  89]]

 ...

 [[ 21  26  25]
  [ 21  26  25]
  [ 21  26  26]
  ...
  [ 94 124 136]
  [ 93 122 136]
  [ 94 123 137]]

 [[ 24  28  29]
  [ 25  29  30]
  [ 25  28  31]
  ...
  [ 93 122 136]
  [ 92 121 134]
  [ 92 121 134]]

 [[ 21  25  27]
  [ 21  25  27]
  [ 24  27  30]
  ...
  [ 90 120 133]
  [ 89 119 132]
  [ 89 119 132]]]
[[[119 130 130]
  [119 130 130]
  [119 130 130]
  ...
  [ 61  83  93]
  [ 61  83  93]
  [ 62  84  94]]

 [[121 132 133]
  [121 132 133]
  [121 132 132]
  ...
  [ 61  83  93]
  [ 64  85  95]
  [ 64  85  95]]

 [[125 136 136]
  [125 136 136]
  [125 136 136]
  ...
  [ 61  83  93]
  [ 63  85  95]
  [ 61  83  93]]

 ...

 [[ 20  26  29]
  [ 22  27  30]
  [ 19  25  28]
  ..

[[[120 127 131]
  [120 127 131]
  [121 129 132]
  ...
  [ 56  80  89]
  [ 59  83  93]
  [ 63  87  96]]

 [[122 130 133]
  [123 131 134]
  [124 132 135]
  ...
  [ 58  82  92]
  [ 60  84  94]
  [ 62  86  95]]

 [[125 135 138]
  [126 136 139]
  [127 137 140]
  ...
  [ 60  84  94]
  [ 63  87  95]
  [ 59  84  91]]

 ...

 [[ 20  26  29]
  [ 20  26  29]
  [ 20  26  29]
  ...
  [ 94 120 135]
  [ 94 121 135]
  [ 94 121 134]]

 [[ 19  25  28]
  [ 19  25  28]
  [ 18  24  27]
  ...
  [ 92 119 134]
  [ 91 118 132]
  [ 91 118 132]]

 [[ 17  22  26]
  [ 18  23  27]
  [ 18  24  27]
  ...
  [ 91 118 133]
  [ 89 116 130]
  [ 88 115 128]]]
[[[118 128 131]
  [118 128 131]
  [118 128 131]
  ...
  [ 60  82  92]
  [ 62  84  94]
  [ 65  86  96]]

 [[120 130 133]
  [121 131 134]
  [122 133 135]
  ...
  [ 61  83  93]
  [ 62  84  94]
  [ 65  86  96]]

 [[125 135 138]
  [126 136 139]
  [126 136 139]
  ...
  [ 61  83  93]
  [ 63  85  95]
  [ 62  84  94]]

 ...

 [[ 22  25  29]
  [ 21  24  28]
  [ 21  24  28]
  ..

[[[118 128 131]
  [116 127 129]
  [118 128 131]
  ...
  [ 61  83  93]
  [ 61  83  93]
  [ 62  84  94]]

 [[119 129 132]
  [120 130 133]
  [121 131 134]
  ...
  [ 59  81  90]
  [ 60  82  91]
  [ 60  82  91]]

 [[122 133 135]
  [123 134 136]
  [123 134 136]
  ...
  [ 57  79  87]
  [ 58  80  88]
  [ 55  78  86]]

 ...

 [[ 14  18  20]
  [ 14  18  20]
  [ 17  23  24]
  ...
  [ 96 123 137]
  [ 97 124 138]
  [ 96 123 137]]

 [[ 16  22  23]
  [ 18  23  25]
  [ 19  24  26]
  ...
  [ 94 121 134]
  [ 94 121 134]
  [ 94 121 134]]

 [[ 18  24  25]
  [ 20  25  27]
  [ 20  23  27]
  ...
  [ 92 120 133]
  [ 90 117 131]
  [ 90 117 131]]]
[[[119 129 132]
  [119 129 132]
  [119 129 132]
  ...
  [ 61  83  93]
  [ 61  83  93]
  [ 62  84  94]]

 [[120 130 133]
  [121 131 134]
  [121 131 134]
  ...
  [ 59  80  90]
  [ 61  83  93]
  [ 61  83  93]]

 [[122 133 135]
  [122 133 135]
  [125 135 138]
  ...
  [ 58  79  89]
  [ 60  82  92]
  [ 59  80  91]]

 ...

 [[ 18  21  24]
  [ 20  23  27]
  [ 20  23  27]
  ..

[[[119 125 131]
  [116 123 129]
  [116 123 129]
  ...
  [ 61  84  91]
  [ 64  86  93]
  [ 62  85  92]]

 [[122 129 134]
  [122 129 134]
  [124 131 137]
  ...
  [ 62  85  93]
  [ 64  86  94]
  [ 61  83  91]]

 [[123 132 136]
  [127 136 139]
  [129 137 140]
  ...
  [ 63  84  93]
  [ 64  85  95]
  [ 60  82  91]]

 ...

 [[ 26  29  33]
  [ 22  25  29]
  [ 21  24  28]
  ...
  [ 95 121 137]
  [ 92 120 136]
  [ 92 120 136]]

 [[ 24  27  31]
  [ 22  25  29]
  [ 21  24  28]
  ...
  [ 93 121 135]
  [ 92 119 134]
  [ 92 119 134]]

 [[ 19  22  26]
  [ 21  24  28]
  [ 21  24  28]
  ...
  [ 94 121 134]
  [ 91 118 132]
  [ 89 116 130]]]
[[[119 125 131]
  [117 124 130]
  [117 124 130]
  ...
  [ 65  83  94]
  [ 67  86  96]
  [ 67  86  96]]

 [[120 128 133]
  [122 129 134]
  [123 130 135]
  ...
  [ 65  85  95]
  [ 66  86  96]
  [ 62  81  92]]

 [[123 132 136]
  [127 136 139]
  [129 137 140]
  ...
  [ 64  85  95]
  [ 60  80  90]
  [ 51  72  82]]

 ...

 [[ 22  26  28]
  [ 22  25  27]
  [ 19  21  23]
  ..

[[[120 132 137]
  [120 132 137]
  [121 133 138]
  ...
  [ 62  83  93]
  [ 63  82  93]
  [ 66  85  95]]

 [[121 133 138]
  [123 134 139]
  [124 136 140]
  ...
  [ 60  82  92]
  [ 64  84  94]
  [ 65  85  95]]

 [[121 133 138]
  [124 136 140]
  [125 137 142]
  ...
  [ 61  83  93]
  [ 65  86  96]
  [ 64  85  95]]

 ...

 [[ 23  27  31]
  [ 24  28  32]
  [ 22  27  31]
  ...
  [ 95 122 136]
  [ 95 122 136]
  [ 94 121 134]]

 [[ 22  27  31]
  [ 21  26  29]
  [ 20  26  29]
  ...
  [ 94 121 134]
  [ 94 121 134]
  [ 94 121 134]]

 [[ 19  25  28]
  [ 19  25  28]
  [ 22  27  31]
  ...
  [ 92 119 133]
  [ 94 121 134]
  [ 94 121 134]]]
[[[119 131 136]
  [119 131 135]
  [118 130 133]
  ...
  [ 63  83  91]
  [ 63  83  91]
  [ 64  84  92]]

 [[121 133 138]
  [121 134 137]
  [123 135 138]
  ...
  [ 63  83  91]
  [ 64  84  92]
  [ 64  84  92]]

 [[122 135 138]
  [122 135 138]
  [124 136 139]
  ...
  [ 67  87  95]
  [ 67  87  95]
  [ 62  82  90]]

 ...

 [[ 23  28  32]
  [ 23  28  32]
  [ 22  27  31]
  ..

[[[118 125 128]
  [118 126 129]
  [119 129 132]
  ...
  [ 59  78  88]
  [ 62  81  92]
  [ 64  84  94]]

 [[122 130 133]
  [124 132 135]
  [124 134 136]
  ...
  [ 54  73  84]
  [ 61  80  90]
  [ 62  81  92]]

 [[123 132 135]
  [125 135 138]
  [126 136 139]
  ...
  [ 62  81  92]
  [ 66  85  95]
  [ 64  84  94]]

 ...

 [[ 20  23  27]
  [ 21  24  28]
  [ 21  24  28]
  ...
  [ 97 121 135]
  [ 97 121 136]
  [ 95 119 133]]

 [[ 21  25  27]
  [ 21  25  27]
  [ 21  26  28]
  ...
  [ 98 123 137]
  [ 96 120 134]
  [ 94 119 133]]

 [[ 21  25  26]
  [ 22  26  28]
  [ 20  27  28]
  ...
  [ 94 119 133]
  [ 92 117 131]
  [ 93 118 132]]]
[[[114 124 127]
  [117 127 129]
  [119 129 132]
  ...
  [ 60  79  89]
  [ 61  80  91]
  [ 61  80  91]]

 [[116 127 129]
  [120 130 133]
  [123 134 136]
  ...
  [ 57  77  87]
  [ 63  83  92]
  [ 63  83  92]]

 [[118 131 133]
  [122 134 137]
  [125 136 139]
  ...
  [ 62  82  90]
  [ 66  85  94]
  [ 66  85  94]]

 ...

 [[ 20  23  27]
  [ 21  24  28]
  [ 21  24  28]
  ..

[[[118 130 135]
  [117 129 133]
  [118 128 133]
  ...
  [ 57  82  89]
  [ 61  86  93]
  [ 61  86  93]]

 [[120 132 137]
  [122 133 138]
  [123 133 138]
  ...
  [ 55  79  87]
  [ 60  84  91]
  [ 61  85  92]]

 [[122 134 139]
  [124 136 140]
  [124 135 141]
  ...
  [ 59  83  90]
  [ 61  84  91]
  [ 61  84  91]]

 ...

 [[ 21  24  28]
  [ 20  23  27]
  [ 19  22  26]
  ...
  [ 91 121 132]
  [ 91 121 132]
  [ 92 122 133]]

 [[ 21  24  28]
  [ 20  23  27]
  [ 20  23  27]
  ...
  [ 92 121 131]
  [ 91 121 131]
  [ 90 121 132]]

 [[ 21  24  28]
  [ 21  24  28]
  [ 21  24  28]
  ...
  [ 93 122 131]
  [ 91 121 131]
  [ 89 120 131]]]
[[[119 128 133]
  [119 128 133]
  [120 129 135]
  ...
  [ 57  78  88]
  [ 64  85  95]
  [ 65  86  96]]

 [[122 132 137]
  [122 132 137]
  [122 132 137]
  ...
  [ 57  78  88]
  [ 61  83  93]
  [ 62  84  94]]

 [[123 133 137]
  [123 133 137]
  [125 135 138]
  ...
  [ 60  82  92]
  [ 61  83  93]
  [ 61  83  93]]

 ...

 [[ 21  24  28]
  [ 20  23  27]
  [ 19  22  26]
  ..

[[[121 131 134]
  [120 130 133]
  [119 129 132]
  ...
  [ 62  81  92]
  [ 67  86  96]
  [ 69  88  98]]

 [[124 133 137]
  [125 135 138]
  [125 135 138]
  ...
  [ 70  88  99]
  [ 74  93 104]
  [ 71  89 100]]

 [[127 135 140]
  [127 135 140]
  [129 137 140]
  ...
  [ 74  91 102]
  [ 78  94 107]
  [ 70  86  99]]

 ...

 [[ 21  26  25]
  [ 20  24  25]
  [ 22  26  28]
  ...
  [ 97 128 138]
  [ 94 127 136]
  [ 93 127 135]]

 [[ 13  17  18]
  [ 17  20  22]
  [ 20  23  26]
  ...
  [ 92 123 134]
  [ 88 120 130]
  [ 88 121 131]]

 [[ 14  18  20]
  [ 18  21  24]
  [ 19  22  26]
  ...
  [ 89 120 130]
  [ 84 116 127]
  [ 81 114 125]]]
[[[121 128 133]
  [122 129 135]
  [123 130 136]
  ...
  [ 69  90 103]
  [ 68  88 103]
  [ 67  87 102]]

 [[126 132 138]
  [127 134 139]
  [127 134 139]
  ...
  [ 58  78  92]
  [ 62  81  96]
  [ 69  88 103]]

 [[128 133 139]
  [129 135 140]
  [131 136 141]
  ...
  [ 50  68  83]
  [ 55  73  88]
  [ 70  88 103]]

 ...

 [[ 23  26  32]
  [ 26  30  35]
  [ 22  26  32]
  ..

[[[122 130 133]
  [123 131 134]
  [123 131 134]
  ...
  [ 62  85  92]
  [ 60  82  90]
  [ 58  80  88]]

 [[125 133 136]
  [128 136 139]
  [128 136 139]
  ...
  [ 60  83  90]
  [ 61  84  91]
  [ 55  78  85]]

 [[127 134 138]
  [129 137 140]
  [130 138 141]
  ...
  [ 61  84  90]
  [ 63  87  92]
  [ 55  78  84]]

 ...

 [[ 23  27  29]
  [ 23  27  29]
  [ 20  24  25]
  ...
  [ 96 125 133]
  [ 97 126 135]
  [ 96 125 134]]

 [[ 19  23  24]
  [ 21  25  27]
  [ 20  24  25]
  ...
  [ 94 122 131]
  [ 95 123 132]
  [ 92 121 130]]

 [[ 13  17  18]
  [ 19  23  24]
  [ 20  24  25]
  ...
  [ 91 120 129]
  [ 89 118 127]
  [ 90 119 128]]]
[[[121 129 132]
  [123 131 134]
  [125 133 136]
  ...
  [ 61  81  89]
  [ 62  82  90]
  [ 64  84  92]]

 [[124 132 135]
  [127 134 138]
  [128 136 139]
  ...
  [ 60  80  88]
  [ 62  82  90]
  [ 66  85  93]]

 [[126 134 138]
  [129 137 140]
  [130 138 141]
  ...
  [ 63  83  92]
  [ 63  83  91]
  [ 62  82  90]]

 ...

 [[ 22  27  26]
  [ 18  22  21]
  [ 10  14  13]
  ..

[[[121 129 132]
  [121 130 133]
  [123 132 135]
  ...
  [ 60  85  93]
  [ 60  84  94]
  [ 63  87  96]]

 [[123 131 134]
  [125 133 136]
  [125 135 138]
  ...
  [ 56  80  88]
  [ 57  81  90]
  [ 58  82  91]]

 [[127 134 138]
  [128 136 139]
  [129 137 140]
  ...
  [ 56  79  86]
  [ 59  82  90]
  [ 59  82  91]]

 ...

 [[ 20  23  27]
  [ 21  24  28]
  [ 21  24  28]
  ...
  [ 95 123 134]
  [ 94 121 133]
  [ 94 121 133]]

 [[ 22  25  29]
  [ 22  25  29]
  [ 21  24  28]
  ...
  [ 95 123 134]
  [ 95 121 133]
  [ 94 120 132]]

 [[ 21  24  28]
  [ 22  25  29]
  [ 22  25  29]
  ...
  [ 94 121 133]
  [ 93 119 130]
  [ 91 116 128]]]
[[[119 129 132]
  [120 130 133]
  [121 132 133]
  ...
  [ 61  82  87]
  [ 62  83  89]
  [ 63  84  90]]

 [[120 130 133]
  [124 134 136]
  [125 135 136]
  ...
  [ 59  79  85]
  [ 60  81  86]
  [ 63  83  88]]

 [[126 135 136]
  [127 136 137]
  [129 138 138]
  ...
  [ 61  81  85]
  [ 63  82  86]
  [ 59  79  82]]

 ...

 [[ 18  22  23]
  [ 20  24  26]
  [ 21  25  27]
  ..

[[[126 129 133]
  [125 128 132]
  [120 123 127]
  ...
  [ 63  82  86]
  [ 63  81  87]
  [ 63  81  87]]

 [[129 133 136]
  [129 133 136]
  [127 130 134]
  ...
  [ 62  81  85]
  [ 65  84  89]
  [ 66  85  91]]

 [[128 134 135]
  [129 135 137]
  [129 134 137]
  ...
  [ 63  81  87]
  [ 66  85  91]
  [ 65  84  90]]

 ...

 [[ 22  23  27]
  [ 24  25  29]
  [ 22  23  27]
  ...
  [ 98 123 135]
  [ 98 123 136]
  [100 125 139]]

 [[ 21  22  26]
  [ 22  23  27]
  [ 22  23  27]
  ...
  [ 96 121 133]
  [ 98 123 135]
  [ 98 123 136]]

 [[ 23  24  28]
  [ 23  24  28]
  [ 23  24  28]
  ...
  [ 94 120 132]
  [ 96 121 133]
  [ 93 119 130]]]
[[[122 133 135]
  [121 131 134]
  [122 133 135]
  ...
  [ 66  83  94]
  [ 68  84  96]
  [ 69  85  98]]

 [[122 133 135]
  [125 135 138]
  [127 137 140]
  ...
  [ 54  70  81]
  [ 58  74  87]
  [ 66  82  95]]

 [[126 136 139]
  [128 138 141]
  [128 138 141]
  ...
  [ 62  78  89]
  [ 64  81  92]
  [ 64  81  92]]

 ...

 [[ 24  25  29]
  [ 19  20  25]
  [ 19  20  25]
  ..